include:
- project: 'subugoe/argo-cd-workflow'
  file: 
    # trigger downstream cross-project pipeline to update the helm chart; triggered on pushing a new tag
    - 'ci-templates/trigger-downstream-pipeline.yml'

# Override variables for included trigger job
trigger-downstream-pipeline:
    variables:
      IMAGE_TAG: ${CI_COMMIT_TAG}
      REPOSITORY_PATH: fe/digis/database-api-helm

variables:
  imageTag: "${CI_COMMIT_TAG}"
  harborPath: "sub-fe/digis"
  dest: "harbor.gwdg.de/${harborPath}/${CI_PROJECT_NAME}:${imageTag}"

build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
    - ''
  script:
  - echo "Pushing image to ${dest}"
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${GITLAB_REGISTRY_TOKEN}" | base64 | tr -d '\n')\"},\"harbor.gwdg.de\":{\"auth\":\"$(printf "%s:%s" "robot\$sub-fe+sub-fe-digis" "${DIGIS_HARBOR_ROBOT_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor 
    --context "${CI_PROJECT_DIR}" 
    --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
    --build-arg build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    --destination ${dest}
  only:
  - tags
