// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "DIGIS Project",
            "url": "https://www.uni-goettingen.de/de/643369.html",
            "email": "digis-info@uni-goettingen.de"
        },
        "license": {
            "name": "Data retrieved is licensed under CC BY-SA 4.0",
            "url": "https://creativecommons.org/licenses/by-sa/4.0/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "Check connection to api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "general"
                ],
                "summary": "Sample request",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queries/authors/{lastName}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get authors by lastname",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "people"
                ],
                "summary": "Retrieve authors by lastname",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Author lastname",
                        "name": "lastName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.People"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queries/fulldata/{samplingfeatureid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get full dataset by samplingfeatureid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fulldata"
                ],
                "summary": "Retrieve full dataset by samplingfeatureid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Samplingfeature identifier",
                        "name": "samplingfeatureid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.FullData"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/queries/sites": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all sites where the longitude and latitude values are within the given range\nOmit query parameters to retrieve all sites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Retrieve all sites within given coordinates",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Minimum (inclusive) latitude",
                        "name": "latMin",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum (inclusive) latitude",
                        "name": "latMax",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum (inclusive) longitude",
                        "name": "lonMin",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum (inclusive) longitude",
                        "name": "lonMax",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Site"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.FullData": {
            "type": "object",
            "properties": {
                "age_Max": {
                    "type": "integer"
                },
                "age_Min": {
                    "type": "integer"
                },
                "batches": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "comment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "elevation_Max": {
                    "type": "integer"
                },
                "elevation_Min": {
                    "type": "integer"
                },
                "inclusion_Type": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "institution": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "item_Group": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "item_Name": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "land_Or_Sea": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "latitude": {
                    "type": "number"
                },
                "latitude_Max": {
                    "type": "string"
                },
                "latitude_Min": {
                    "type": "string"
                },
                "loc_Data": {},
                "location_Names": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "location_Num": {
                    "type": "integer"
                },
                "location_Types": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "longitude": {
                    "type": "number"
                },
                "longitude_Max": {
                    "type": "string"
                },
                "longitude_Min": {
                    "type": "string"
                },
                "material": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mineral": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "references": {},
                "rock_Class": {
                    "type": "string"
                },
                "rock_Texture": {
                    "type": "string"
                },
                "rock_Type": {
                    "type": "string"
                },
                "sampleIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sample_Num": {
                    "type": "integer"
                },
                "standard_Names": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "standard_Values": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    }
                },
                "tectonic_Setting": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "unique_id": {
                    "type": "string"
                },
                "units": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "model.People": {
            "type": "object",
            "properties": {
                "personFirstName": {
                    "type": "string"
                },
                "personId": {
                    "type": "integer"
                },
                "personLastName": {
                    "type": "string"
                }
            }
        },
        "model.Site": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "locationPrecision": {
                    "type": "number"
                },
                "locationPrecisionComment": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "samplingFeatureID": {
                    "type": "integer"
                },
                "setting": {
                    "type": "string"
                },
                "siteDescription": {
                    "type": "string"
                },
                "siteTypeCV": {
                    "type": "string"
                },
                "spatialReferenceID": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{"https"},
	Title:            "DIGIS Database API",
	Description:      "This is the database api for the new GeoROC datamodel",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
